version: 2
jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm install @cypress/commit-message-install
      # now install just a specific version of Cypress (from commit message)
      # or latest version of Cypress
      - run:
          name: Install Cypress
          command: $(npm bin)/commit-message-install --else "npm i cypress"
      - run: $(npm bin)/cypress verify
      - run: npm test

      # if needed, set the Cypress commit status
      - run:
          when: on_success
          name: Set status check
          command: $(npm bin)/set-status --state success --description "on CircleCI"
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "on CircleCI"

workflows:
  version: 2
  build:
    jobs:
      - test
