name: Validate initial app state

on: push

jobs:
  single-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          working-directory: ./src/clients/bar